apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pp-service-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-app
  replicas: 1
  template: 
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: pp-service
        image: pp010/dockerapp
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8081
          name: management