apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: pp010/service1
        ports:
        - containerPort: 8080
          name: server